<a href="https://colab.research.google.com/github/DataCrusade1999/Tensorflow/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import numpy as np
import tensorflow as tf
import cProfile
import matplotlib.pyplot as plt

In [2]:
a = tf.constant([[1, 2],[3, 4]])
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [3]:
b = tf.constant([[1, 2],[3, 4]])
print(b)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [4]:
c = tf.add(a, 1)
print(c)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [5]:
print(a*b)

tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)


In [6]:
var=np.multiply(a,b)
print(var)

[[ 1  4]
 [ 9 16]]


In [7]:
var=tf.constant([[3,4,5],[4,5,6]])
var.numpy()

array([[3, 4, 5],
       [4, 5, 6]], dtype=int32)

In [8]:
a=tf.constant([[0,1,3],[3,4,3]])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 3],
       [3, 4, 3]], dtype=int32)>

In [9]:
a=tf.ones([3,3],dtype='int32')
b=tf.constant([[1,2],
               [3,4],
               [5,6]],dtype='int32')

In [10]:
max_value=tf.reduce_max(b)
max_value

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [11]:
print(a @ b)

tf.Tensor(
[[ 9 12]
 [ 9 12]
 [ 9 12]], shape=(3, 2), dtype=int32)


https://www.tensorflow.org/guide/tensor#about_shapes

In [12]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])

print(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(3, 2, 4, 5), dtype=float32)


In [13]:
rank_2_tensor=tf.constant([[1,2],
                           [3,4],
                           [5,6]])

In [14]:
print(rank_2_tensor.numpy())

[[1 2]
 [3 4]
 [5 6]]


In [15]:
print(rank_2_tensor[1::].numpy())

[[3 4]
 [5 6]]


In [16]:
# Shape returns a `TensorShape` object that shows the size on each dimension
x = tf.constant([[1], [2], [3]])
print(x.ndim)
print(x.shape)

2
(3, 1)


In [17]:
reshaped=tf.reshape(x,[1,3])
print(reshaped.shape)
print(x.shape)

(1, 3)
(3, 1)


In [18]:
rank_4_tensor.dtype

tf.float32

In [19]:
rank_5_tensor=tf.ones([2,2,4,4])
print(rank_5_tensor)

tf.Tensor(
[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]], shape=(2, 2, 4, 4), dtype=float32)


In [20]:
rank_5_tensor=tf.cast(rank_5_tensor,tf.uint8)
print(rank_5_tensor)

tf.Tensor(
[[[[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]]


 [[[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]]], shape=(2, 2, 4, 4), dtype=uint8)


In [21]:
y = tf.range(5)
print(y)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


In [22]:
y=tf.reshape(y,[5,1])
print(y)

tf.Tensor(
[[0]
 [1]
 [2]
 [3]
 [4]], shape=(5, 1), dtype=int32)


In [23]:
max_val=tf.argmax(y)
print(max_val)

tf.Tensor([4], shape=(1,), dtype=int64)


In [24]:
z=tf.broadcast_to([1],[3,3])
print(z)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)


https://www.tensorflow.org/guide/tensor#string_tensors

In [25]:
string=tf.constant("Ashutosh Pandey")
print(string)

tf.Tensor(b'Ashutosh Pandey', shape=(), dtype=string)


In [26]:
byte_string=tf.strings.bytes_split(string)
byte_decode=tf.io.decode_raw(string,tf.uint8)
print(byte_decode)
print(byte_string)

tf.Tensor([ 65 115 104 117 116 111 115 104  32  80  97 110 100 101 121], shape=(15,), dtype=uint8)
tf.Tensor(
[b'A' b's' b'h' b'u' b't' b'o' b's' b'h' b' ' b'P' b'a' b'n' b'd' b'e'
 b'y'], shape=(15,), dtype=string)


In [27]:
string=tf.strings.split(string,sep=" ")
print(string)

tf.Tensor([b'Ashutosh' b'Pandey'], shape=(2,), dtype=string)


In [28]:
string=tf.strings.split(string)
print(string)

<tf.RaggedTensor [[b'Ashutosh'], [b'Pandey']]>


In [29]:
tensor=tf.ragged.constant([[1,2],[2]])
print(tensor.shape)

(2, None)


In [30]:
unicode_tensor=tf.constant("✅😀")
unicode_decode=tf.strings.unicode_decode(unicode_tensor,"UTF-8")
print(unicode_decode)

tf.Tensor([  9989 128512], shape=(2,), dtype=int32)


https://www.tensorflow.org/guide/tensor#sparse_tensors

In [31]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[4, 4])
print(sparse_tensor ,"\n")

# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(4, 4), dtype=int32)


In [32]:
y=tf.Variable([[1.0, 2.0], [3.0, 4.0]])
print(y)
print(tf.convert_to_tensor(y))
print(y.numpy())
print(tf.argmax(y))

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
[[1. 2.]
 [3. 4.]]
tf.Tensor([1 1], shape=(2,), dtype=int64)


In [33]:
a=tf.Variable([1,2])
try:
  a.assign([3,4,6])
  print(a)

except Exception as e:
  #print(f"{type(e).__name__}:{e}" )
  print(type(e).__name__)


ValueError


In [34]:
a=tf.Variable([1,2,3],name="Tensor A")
b=tf.Variable(a,name="Tensor B")
print(b)
#Updating Tensor A
a.assign([4,5,8])
a.assign_add([5,6,7])
print(a)
a.assign_sub([5,6,7])
print(a)

<tf.Variable 'Tensor B:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
<tf.Variable 'Tensor A:0' shape=(3,) dtype=int32, numpy=array([ 9, 11, 15], dtype=int32)>
<tf.Variable 'Tensor A:0' shape=(3,) dtype=int32, numpy=array([4, 5, 8], dtype=int32)>


Although variables are important for differentiation, some variables will not need to be differentiated. You can turn off gradients for a variable by setting trainable to false at creation. An example of a variable that would not need gradients is a training step counter.

In [35]:
step_counter = tf.Variable(1, trainable=False)
print(step_counter)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>


#Gradient
https://www.tensorflow.org/guide/autodiff#automatic_differentiation_and_gradients

In [36]:
variable=tf.Variable(3.0)

with tf.GradientTape() as tape:
  target=variable**2

dy_dx=tape.gradient(target,variable)

dy_dx.numpy()

6.0

In [37]:
layer = tf.keras.layers.Dense(8,activation='relu')
x = tf.constant([[1., 2., 3.]])

with tf.GradientTape() as tape:
  # Forward pass
  y = layer(x)
  loss = tf.reduce_mean(y**2)

# Calculate gradients with respect to every trainable variable
grad = tape.gradient(loss, layer.trainable_variables)

In [38]:
for var, g in zip(layer.trainable_variables, grad):
  print(f'{var.name}, shape: {g.shape}')

dense/kernel:0, shape: (3, 8)
dense/bias:0, shape: (8,)


In [39]:
[var.name for var in tape.watched_variables()]

['dense/kernel:0', 'dense/bias:0']

In [40]:
x2 = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]], dtype=tf.float32)

y = np.mean(x2, axis=1)
y

array([1.5, 3.5], dtype=float32)

In [41]:
class Dense(tf.Module):
  def __init__(self, in_features, out_features, name=None):
    super().__init__(name=name)
    self.w = tf.Variable(
      tf.random.normal([in_features, out_features]), name='w')
    self.b = tf.Variable(tf.zeros([out_features]), name='b')
  def __call__(self, x):
    y = tf.matmul(x, self.w) + self.b
    return tf.nn.relu(y)
class SequentialModule(tf.Module):
  def __init__(self, name=None):
    super().__init__(name=name)

    self.dense_1 = Dense(in_features=3, out_features=3)
    self.dense_2 = Dense(in_features=3, out_features=2)

  def __call__(self, x):
    x = self.dense_1(x)
    return self.dense_2(x)

# You have made a model!
my_model = SequentialModule(name="the_model")

# Call it, with random results
print("Model results:", my_model(tf.constant([[2.0, 2.0, 2.0]])))

Model results: tf.Tensor([[0.        1.3292265]], shape=(1, 2), dtype=float32)
